name: Docker Compose CI

on:
  workflow_dispatch:
  pull_request:

env:
  COMPOSE_FILE: compose.yml:compose.ci.yml

jobs:
  docker-compose-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the stack
        run: |
          DOCKER_BUILDKIT=1 docker compose up --quiet-pull --no-color --remove-orphans --exit-code-from ci
